name: Twitch Archive

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        run: pip install -U yt-dlp

      - name: Install TwitchDownloaderCLI
        run: |
         API_URL="https://api.github.com/repos/lay295/TwitchDownloader/releases/latest"
         DOWNLOAD_URL=$(curl -s $API_URL | grep browser_download_url | grep linux-x64 | cut -d '"' -f 4)
         wget "$DOWNLOAD_URL" -O TwitchDownloaderCLI
         chmod +x TwitchDownloaderCLI
         sudo mv TwitchDownloaderCLI /usr/local/bin/TwitchDownloaderCLI

      - name: Write cookies file
        run: echo "${{ secrets.TWITCH_COOKIES }}" > cookies.txt

      - name: Run fetch
        run: python scripts/fetch_vods.py

      - name: Normalize chats
        run: python scripts/normalize_chat.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Archive Twitch VODs" || echo "No changes"
          git push
